# Generated by Django 4.2.6 on 2023-10-25 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_booking_menu_delete_restaurant"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="MenuItem",
        ),
    ]
